### ISSUE TITLE
concerns regarding crypto being introduced as a feature

### ISSUE THREAD

**Issue by ddodogames** [InikoMatthewPro/dodobot-hosting#2]
it appears that you added crypto as a feature where people earn it from my server only, first of all, we're not interested in crypto, besides i don't think that everyone wants crypto, i kindly ask you to remove that tbh

**Comment by InikoPro** [comment]
Ok im sorry, i remove was crypto.

**Comment by InikoPro** [comment]
> i don't think that everyone wants crypto

Wait, you know crypto? Or not?

**Comment by ddodogames** [comment]
> > i don't think that everyone wants crypto
> 
> Wait, you know crypto? Or not?

i know it but none of us are using it

**Comment by InikoPro** [comment]
ok
